---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: user-management-centos7
    image: "centos:7"
    pre_build_image: true
  - name: user-management-almalinux8
    image: "almalinux:8"
    pre_build_image: true
  - name: user-management-debian10
    image: "debian:10"
    pre_build_image: true
  - name: user-management-debian11
    image: "debian:11"
    pre_build_image: true
  - name: user-management-debian-testing
    image: "debian:testing"
    pre_build_image: true
  - name: user-management-fedora36
    image: "fedora:36"
    pre_build_image: true
  - name: user-management-ubuntu2004
    image: "ubuntu:20.04"
    pre_build_image: true
  - name: user-management-ubuntu2204
    image: "ubuntu:22.04"
    pre_build_image: true
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  flake8
role_name_check: 1
