---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: user-management-centos7
    image: "geerlingguy/docker-centos7-ansible:latest"
    pre_build_image: true
  - name: user-management-centos8
    image: "geerlingguy/docker-centos8-ansible:latest"
    pre_build_image: true
  - name: user-management-debian9
    image: "geerlingguy/docker-debian9-ansible:latest"
    pre_build_image: true
  - name: user-management-debian10
    image: "geerlingguy/docker-debian10-ansible:latest"
    pre_build_image: true
  - name: user-management-fedora34
    image: "geerlingguy/docker-fedora34-ansible:latest"
    pre_build_image: true
  - name: user-management-ubuntu1804
    image: "geerlingguy/docker-ubuntu1804-ansible:latest"
    pre_build_image: true
  - name: user-management-ubuntu2004
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
